version: 2.1

executors:
  go-executor:
    docker:
      - image: cimg/go:1.23
    working_directory: ~/project

jobs:
  build_binary:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: "Recreate Go Workspace"
          command: |
            go work init
            go work use -r .
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.mod" }}
      - run:
          name: "Build Dashboard Server"
          command: go build -o bin/dashboard-server ./cmd/dashboard-server/main.go
      - save_cache:
          key: go-mod-v4-{{ checksum "go.mod" }}
          paths:
            - "/go/pkg/mod"
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    executor: go-executor
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: "Run Unit Tests"
          command: go test -v ./...

  build_docker:
    machine:
      image: ubuntu-2204:2023.10.1
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: "Build Docker Image"
          command: |
            docker build -t dashboard-api:latest \
              -f deploy/docker/Dashboard.Dockerfile .

workflows:
  version: 2
  main_pipeline:
    jobs:
      - build_binary
      - test:
          requires:
            - build_binary
      - build_docker:
          requires:
            - test