// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/jassus213/GoBoard/dashboard/domain"

	mock "github.com/stretchr/testify/mock"
)

// DashboardRepository is an autogenerated mock type for the DashboardRepository type
type DashboardRepository struct {
	mock.Mock
}

type DashboardRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *DashboardRepository) EXPECT() *DashboardRepository_Expecter {
	return &DashboardRepository_Expecter{mock: &_m.Mock}
}

// AddMemberToDashboard provides a mock function with given fields: ctx, dashboard, member, score
func (_m *DashboardRepository) AddMemberToDashboard(ctx context.Context, dashboard string, member string, score float64) error {
	ret := _m.Called(ctx, dashboard, member, score)

	if len(ret) == 0 {
		panic("no return value specified for AddMemberToDashboard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, float64) error); ok {
		r0 = rf(ctx, dashboard, member, score)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DashboardRepository_AddMemberToDashboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMemberToDashboard'
type DashboardRepository_AddMemberToDashboard_Call struct {
	*mock.Call
}

// AddMemberToDashboard is a helper method to define mock.On call
//   - ctx context.Context
//   - dashboard string
//   - member string
//   - score float64
func (_e *DashboardRepository_Expecter) AddMemberToDashboard(ctx interface{}, dashboard interface{}, member interface{}, score interface{}) *DashboardRepository_AddMemberToDashboard_Call {
	return &DashboardRepository_AddMemberToDashboard_Call{Call: _e.mock.On("AddMemberToDashboard", ctx, dashboard, member, score)}
}

func (_c *DashboardRepository_AddMemberToDashboard_Call) Run(run func(ctx context.Context, dashboard string, member string, score float64)) *DashboardRepository_AddMemberToDashboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(float64))
	})
	return _c
}

func (_c *DashboardRepository_AddMemberToDashboard_Call) Return(_a0 error) *DashboardRepository_AddMemberToDashboard_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DashboardRepository_AddMemberToDashboard_Call) RunAndReturn(run func(context.Context, string, string, float64) error) *DashboardRepository_AddMemberToDashboard_Call {
	_c.Call.Return(run)
	return _c
}

// AddMembersBatch provides a mock function with given fields: ctx, dashboard, members
func (_m *DashboardRepository) AddMembersBatch(ctx context.Context, dashboard string, members []domain.DashboardRecord) error {
	ret := _m.Called(ctx, dashboard, members)

	if len(ret) == 0 {
		panic("no return value specified for AddMembersBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []domain.DashboardRecord) error); ok {
		r0 = rf(ctx, dashboard, members)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DashboardRepository_AddMembersBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMembersBatch'
type DashboardRepository_AddMembersBatch_Call struct {
	*mock.Call
}

// AddMembersBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - dashboard string
//   - members []domain.DashboardRecord
func (_e *DashboardRepository_Expecter) AddMembersBatch(ctx interface{}, dashboard interface{}, members interface{}) *DashboardRepository_AddMembersBatch_Call {
	return &DashboardRepository_AddMembersBatch_Call{Call: _e.mock.On("AddMembersBatch", ctx, dashboard, members)}
}

func (_c *DashboardRepository_AddMembersBatch_Call) Run(run func(ctx context.Context, dashboard string, members []domain.DashboardRecord)) *DashboardRepository_AddMembersBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]domain.DashboardRecord))
	})
	return _c
}

func (_c *DashboardRepository_AddMembersBatch_Call) Return(_a0 error) *DashboardRepository_AddMembersBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DashboardRepository_AddMembersBatch_Call) RunAndReturn(run func(context.Context, string, []domain.DashboardRecord) error) *DashboardRepository_AddMembersBatch_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDashboard provides a mock function with given fields: ctx, dashboard
func (_m *DashboardRepository) DeleteDashboard(ctx context.Context, dashboard string) error {
	ret := _m.Called(ctx, dashboard)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDashboard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, dashboard)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DashboardRepository_DeleteDashboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDashboard'
type DashboardRepository_DeleteDashboard_Call struct {
	*mock.Call
}

// DeleteDashboard is a helper method to define mock.On call
//   - ctx context.Context
//   - dashboard string
func (_e *DashboardRepository_Expecter) DeleteDashboard(ctx interface{}, dashboard interface{}) *DashboardRepository_DeleteDashboard_Call {
	return &DashboardRepository_DeleteDashboard_Call{Call: _e.mock.On("DeleteDashboard", ctx, dashboard)}
}

func (_c *DashboardRepository_DeleteDashboard_Call) Run(run func(ctx context.Context, dashboard string)) *DashboardRepository_DeleteDashboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *DashboardRepository_DeleteDashboard_Call) Return(_a0 error) *DashboardRepository_DeleteDashboard_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DashboardRepository_DeleteDashboard_Call) RunAndReturn(run func(context.Context, string) error) *DashboardRepository_DeleteDashboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetTopMembers provides a mock function with given fields: ctx, dashboard, top
func (_m *DashboardRepository) GetTopMembers(ctx context.Context, dashboard string, top int64) ([]domain.DashboardRecord, error) {
	ret := _m.Called(ctx, dashboard, top)

	if len(ret) == 0 {
		panic("no return value specified for GetTopMembers")
	}

	var r0 []domain.DashboardRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) ([]domain.DashboardRecord, error)); ok {
		return rf(ctx, dashboard, top)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) []domain.DashboardRecord); ok {
		r0 = rf(ctx, dashboard, top)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DashboardRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, dashboard, top)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DashboardRepository_GetTopMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopMembers'
type DashboardRepository_GetTopMembers_Call struct {
	*mock.Call
}

// GetTopMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - dashboard string
//   - top int64
func (_e *DashboardRepository_Expecter) GetTopMembers(ctx interface{}, dashboard interface{}, top interface{}) *DashboardRepository_GetTopMembers_Call {
	return &DashboardRepository_GetTopMembers_Call{Call: _e.mock.On("GetTopMembers", ctx, dashboard, top)}
}

func (_c *DashboardRepository_GetTopMembers_Call) Run(run func(ctx context.Context, dashboard string, top int64)) *DashboardRepository_GetTopMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *DashboardRepository_GetTopMembers_Call) Return(_a0 []domain.DashboardRecord, _a1 error) *DashboardRepository_GetTopMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DashboardRepository_GetTopMembers_Call) RunAndReturn(run func(context.Context, string, int64) ([]domain.DashboardRecord, error)) *DashboardRepository_GetTopMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalMembers provides a mock function with given fields: ctx, dashboard
func (_m *DashboardRepository) GetTotalMembers(ctx context.Context, dashboard string) (int64, error) {
	ret := _m.Called(ctx, dashboard)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalMembers")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, dashboard)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, dashboard)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, dashboard)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DashboardRepository_GetTotalMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalMembers'
type DashboardRepository_GetTotalMembers_Call struct {
	*mock.Call
}

// GetTotalMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - dashboard string
func (_e *DashboardRepository_Expecter) GetTotalMembers(ctx interface{}, dashboard interface{}) *DashboardRepository_GetTotalMembers_Call {
	return &DashboardRepository_GetTotalMembers_Call{Call: _e.mock.On("GetTotalMembers", ctx, dashboard)}
}

func (_c *DashboardRepository_GetTotalMembers_Call) Run(run func(ctx context.Context, dashboard string)) *DashboardRepository_GetTotalMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *DashboardRepository_GetTotalMembers_Call) Return(_a0 int64, _a1 error) *DashboardRepository_GetTotalMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DashboardRepository_GetTotalMembers_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *DashboardRepository_GetTotalMembers_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementMemberScore provides a mock function with given fields: ctx, dashboard, member, increment
func (_m *DashboardRepository) IncrementMemberScore(ctx context.Context, dashboard string, member string, increment float64) error {
	ret := _m.Called(ctx, dashboard, member, increment)

	if len(ret) == 0 {
		panic("no return value specified for IncrementMemberScore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, float64) error); ok {
		r0 = rf(ctx, dashboard, member, increment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DashboardRepository_IncrementMemberScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementMemberScore'
type DashboardRepository_IncrementMemberScore_Call struct {
	*mock.Call
}

// IncrementMemberScore is a helper method to define mock.On call
//   - ctx context.Context
//   - dashboard string
//   - member string
//   - increment float64
func (_e *DashboardRepository_Expecter) IncrementMemberScore(ctx interface{}, dashboard interface{}, member interface{}, increment interface{}) *DashboardRepository_IncrementMemberScore_Call {
	return &DashboardRepository_IncrementMemberScore_Call{Call: _e.mock.On("IncrementMemberScore", ctx, dashboard, member, increment)}
}

func (_c *DashboardRepository_IncrementMemberScore_Call) Run(run func(ctx context.Context, dashboard string, member string, increment float64)) *DashboardRepository_IncrementMemberScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(float64))
	})
	return _c
}

func (_c *DashboardRepository_IncrementMemberScore_Call) Return(_a0 error) *DashboardRepository_IncrementMemberScore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DashboardRepository_IncrementMemberScore_Call) RunAndReturn(run func(context.Context, string, string, float64) error) *DashboardRepository_IncrementMemberScore_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementMembersBatch provides a mock function with given fields: ctx, dashboard, increments
func (_m *DashboardRepository) IncrementMembersBatch(ctx context.Context, dashboard string, increments []domain.DashboardRecord) error {
	ret := _m.Called(ctx, dashboard, increments)

	if len(ret) == 0 {
		panic("no return value specified for IncrementMembersBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []domain.DashboardRecord) error); ok {
		r0 = rf(ctx, dashboard, increments)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DashboardRepository_IncrementMembersBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementMembersBatch'
type DashboardRepository_IncrementMembersBatch_Call struct {
	*mock.Call
}

// IncrementMembersBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - dashboard string
//   - increments []domain.DashboardRecord
func (_e *DashboardRepository_Expecter) IncrementMembersBatch(ctx interface{}, dashboard interface{}, increments interface{}) *DashboardRepository_IncrementMembersBatch_Call {
	return &DashboardRepository_IncrementMembersBatch_Call{Call: _e.mock.On("IncrementMembersBatch", ctx, dashboard, increments)}
}

func (_c *DashboardRepository_IncrementMembersBatch_Call) Run(run func(ctx context.Context, dashboard string, increments []domain.DashboardRecord)) *DashboardRepository_IncrementMembersBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]domain.DashboardRecord))
	})
	return _c
}

func (_c *DashboardRepository_IncrementMembersBatch_Call) Return(_a0 error) *DashboardRepository_IncrementMembersBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DashboardRepository_IncrementMembersBatch_Call) RunAndReturn(run func(context.Context, string, []domain.DashboardRecord) error) *DashboardRepository_IncrementMembersBatch_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMemberFromDashboard provides a mock function with given fields: ctx, dashboard, member
func (_m *DashboardRepository) RemoveMemberFromDashboard(ctx context.Context, dashboard string, member string) error {
	ret := _m.Called(ctx, dashboard, member)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMemberFromDashboard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, dashboard, member)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DashboardRepository_RemoveMemberFromDashboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMemberFromDashboard'
type DashboardRepository_RemoveMemberFromDashboard_Call struct {
	*mock.Call
}

// RemoveMemberFromDashboard is a helper method to define mock.On call
//   - ctx context.Context
//   - dashboard string
//   - member string
func (_e *DashboardRepository_Expecter) RemoveMemberFromDashboard(ctx interface{}, dashboard interface{}, member interface{}) *DashboardRepository_RemoveMemberFromDashboard_Call {
	return &DashboardRepository_RemoveMemberFromDashboard_Call{Call: _e.mock.On("RemoveMemberFromDashboard", ctx, dashboard, member)}
}

func (_c *DashboardRepository_RemoveMemberFromDashboard_Call) Run(run func(ctx context.Context, dashboard string, member string)) *DashboardRepository_RemoveMemberFromDashboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *DashboardRepository_RemoveMemberFromDashboard_Call) Return(_a0 error) *DashboardRepository_RemoveMemberFromDashboard_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DashboardRepository_RemoveMemberFromDashboard_Call) RunAndReturn(run func(context.Context, string, string) error) *DashboardRepository_RemoveMemberFromDashboard_Call {
	_c.Call.Return(run)
	return _c
}

// ViewMemberRank provides a mock function with given fields: ctx, dashboard, memberId
func (_m *DashboardRepository) ViewMemberRank(ctx context.Context, dashboard string, memberId string) (int64, error) {
	ret := _m.Called(ctx, dashboard, memberId)

	if len(ret) == 0 {
		panic("no return value specified for ViewMemberRank")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return rf(ctx, dashboard, memberId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = rf(ctx, dashboard, memberId)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, dashboard, memberId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DashboardRepository_ViewMemberRank_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ViewMemberRank'
type DashboardRepository_ViewMemberRank_Call struct {
	*mock.Call
}

// ViewMemberRank is a helper method to define mock.On call
//   - ctx context.Context
//   - dashboard string
//   - memberId string
func (_e *DashboardRepository_Expecter) ViewMemberRank(ctx interface{}, dashboard interface{}, memberId interface{}) *DashboardRepository_ViewMemberRank_Call {
	return &DashboardRepository_ViewMemberRank_Call{Call: _e.mock.On("ViewMemberRank", ctx, dashboard, memberId)}
}

func (_c *DashboardRepository_ViewMemberRank_Call) Run(run func(ctx context.Context, dashboard string, memberId string)) *DashboardRepository_ViewMemberRank_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *DashboardRepository_ViewMemberRank_Call) Return(_a0 int64, _a1 error) *DashboardRepository_ViewMemberRank_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DashboardRepository_ViewMemberRank_Call) RunAndReturn(run func(context.Context, string, string) (int64, error)) *DashboardRepository_ViewMemberRank_Call {
	_c.Call.Return(run)
	return _c
}

// NewDashboardRepository creates a new instance of DashboardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDashboardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DashboardRepository {
	mock := &DashboardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
