version: '3.8'
name: dashboard-api

services:
  redis:
    image: redis:7.2-alpine
    container_name: dashboard-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  redis-insight:
    image: redis/redisinsight:latest
    container_name: dashboard-redis-insight
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - redis_insight_data:/data
    depends_on:
      - redis

volumes:
  redis_data:
  redis_insight_data: